### ISSUE TITLE
Not working with {{string}} 

### ISSUE THREAD

**Issue by Taewa** [EliasBF/angular-typing-animation#3]
Hi

How can I use with dynamic text?

For example, 
```
<span typingAnimation [typeSpeed]="50" [condition]="start" [startDelay]="1000">
  {{test}}
</span>
```

And in my component 

```
@Component({...})
export class MyComponent implements OnInit {
  test = 'abcdefg';
  ...
}
```

It seems not working with dynamic text.
Let me know if I missed anything.
Thanks!

**Comment by eliashbf** [comment]
Hi

It is not possible in versions below 0.5.4, because the component is responsible first of initializing the directive before making the link, and unfortunately the animation after taking the reference of the text element, creates a new copy of its content and this does not change again.

In version 0.5.4 it has been corrected and now the animation expects a different value of empty before starting.

You can check that here:
[https://embed.plnkr.co/CefhwrE7yFLAciY7ZsPU/](https://embed.plnkr.co/CefhwrE7yFLAciY7ZsPU/)

I hope it helps you
